import ClientOnly from "./components/ClicentOnly";
import RegisterModel from "./components/models/RegisterModel";
import LoginModel from "./components/models/LoginModel";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import ToasterProvider from "./providers/ToasterProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wanderers Retreat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <ToasterProvider />
          <LoginModel />
          <RegisterModel />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
